<div class="post-text" itemprop="text">
<p>I was installing scipy for theano in virtualenv, it fails right after the start the installation. And it says it fails with error code -11. Could anyone can help me with this, what is the error code 11?</p>
<p>Here is the full trace of the error, from the beginning of when I run the command:</p>
<pre><code>(dl)[haohan@sirius deeplearning]$ pip install theano
Requirement already satisfied (use --upgrade to upgrade): theano in ./dl/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy&gt;=1.5.0 in ./dl/lib/python2.7/site-   packages (from theano)
Downloading/unpacking scipy&gt;=0.7.2 (from theano)
Downloading scipy-0.14.0.tar.gz (10.2MB): 10.2MB downloaded
Running setup.py (path:/home/haohan/deeplearning/dl/build/scipy/setup.py) egg_info for package scipy

    warning: no previously-included files matching '*_subr_*.f' found under directory 'scipy/linalg/src/id_dist/src'
    no previously-included directories found matching 'scipy/special/tests/data/boost'
    no previously-included directories found matching 'scipy/special/tests/data/gsl'
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/source/generated'
    no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.bak' found anywhere in distribution
    warning: no previously-included files matching '*.swp' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
Installing collected packages: scipy
    Running setup.py install for scipy
Cleaning up...
Command /home/haohan/deeplearning/dl/bin/python -c "import setuptools, tokenize;__file__='/home/haohan/deeplearning/dl/build/scipy/setup.py';
exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" 
install --record /tmp/pip-svx8Wr-record/install-record.txt --single-version-externally-managed --compile --install-headers 
/home/haohan/deeplearning/dl/include/site/python2.7 failed with error code -11 in /home/haohan/deeplearning/dl/build/scipy
Storing debug log for failure in /home/haohan/.pip/pip.log
</code></pre>
<p>I break the second last line into several lines, for the convenience of reading.<br/>
I think this is very strange that the error occurs barely after the installation starts and I have just use pip to install numpy successfully, so it's unlikely to be the problem of pip. Then, where is the problem? How should I fix it?</p>
<p>Could it be related with the system? But I guess I cannot print the system information out since I don't have sudo permission...</p>
<p>Could it because that our cluster is too old? That's the only explanation that I can think of. </p>
<p>Thanks a lot!</p>
</div>
<div class="post-text" itemprop="text">
<p>Have you tried updating setuptools?</p>
<pre><code>pip install --upgrade setuptools
</code></pre>
<p>Then try installing theano again. </p>
<p>When I encountered this problem while developing my own package, the root cause was with imports in <code>setup.py</code>. I changed what <code>setup.py</code> imported and then it worked. Maybe <code>theano</code>'s setup is importing a package which has an incompatible version?</p>
<p>If the problem isn't solved by updating packages or editing imports in setup, you can try to debug by using the <code>vvv</code> flag to get more information, as in <code>pip install -vvv theano</code>. </p>
<p>As for the error code you're seeing:</p>
<blockquote>
<p>A negative value -N indicates that the child was terminated by signal
  N (Unix only)</p>
</blockquote>
<p><a href="https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode" rel="nofollow noreferrer">https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode</a></p>
<p>Code 11 means segfault in *nix, although <code>os.strerror(11)</code> reports "Resource temporarily unavailable". Since I get segfaults when I attempt python setup.py egg_info, I'm betting it's the first (segfault) definition of 11 that's relevant.</p>
<p>If your segfault dumped a core, it's probably in <code>/var/lib/systemd/coredump/</code> if you're using systemd.
<a href="https://unix.stackexchange.com/a/349433/183163">https://unix.stackexchange.com/a/349433/183163</a>
If you can't find a core, check <code>ulimit -c</code>. If it reports <code>0</code>, run <code>ulimit -c unlimited</code> to enable core dumping. You can get the full path to the most recent dump file by <code>ls -rtd /var/lib/systemd/coredump/* | tail -1</code></p>
<p>To read the dump, you can use <code>gdb</code>. For example:</p>
<pre><code>gdb python /var/lib/systemd/coredump/core.python.6146.f06ba728dae74cfbbaf80acb8d392dd5.4477.1524677641000000.lz4
</code></pre>
</div>
<span class="comment-copy">What does <code>/home/haohan/.pip/pip.log</code> show?</span>
<span class="comment-copy">@JohnZwinck thanks. It shows exactly what has been showed in this post, nothing more...</span>
<span class="comment-copy">I'm having the same error code thrown at me. See here: <a href="http://stackoverflow.com/q/34595603/1391441">stackoverflow.com/q/34595603/1391441</a></span>
