link:
library/asyncio-api-index.html#exceptions

docs:

ExceptionsÂ¶






asyncio.TimeoutError
Raised on timeout by functions like wait_for().
Keep in mind that asyncio.TimeoutError is unrelated
to the built-in TimeoutError exception.

asyncio.CancelledError
Raised when a Task is cancelled. See also Task.cancel().



Examples

Handling CancelledError to run code on cancellation request.
See also the full list of
asyncio-specific exceptions.

