Natural Text
I am new to python. I wanted to test if my code throws an exception. I got the code from here: How do you test that a Python function throws an exception?Now, I also want to display a message if the exception is not thrown. How do I do that ? The python docs do not mention it clearly. I added the message after "compulsory_argument" and it failed.EDIT: I tried the first answer with modifications and got an exception. What is my mistake here ?Error:
As of python 3.3, assertRaises can be used as a context manager with a message:Results in
Now, I also want to display a message if the exception is not thrown. How do I do that ?The general philosophy of unittest is for the tests to be silent when they succeed and only become verbose when they fail.  Accordingly, the API provides a "msg" keyword argument for the unsuccessful case but does not offer an alternative for the successful case.That said, another part of the philosophy works in your favor.  In general, test cases internally raise an exception when a testcase fails.  That means that if you want to display a message when there is a success, you just add another statement after the test:


Answer URL
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises
